workflows:
  flutter-app:
    name: Build Flutter APK
    environment:
      flutter: stable
    scripts:
      - cd MyStandInSupportApp
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - MyStandInSupportApp/build/app/outputs/flutter-apk/app-release.apk
