codemagic.yaml
``>

---

### **STEP 4: Paste This Code Into the File**
Copy and paste this into the file editor:

```yaml
workflows:
  flutter-app:
    name: Build Flutter APK
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

